config/routes.rb
Rails.application.routes.draw do
  

  
        root to: "home#index"
        devise_for :users

        resources :aclasses
        resources :testdata , :controller=>"gradelevels", :as=>:gradelevels
        resources :termdata
        resources :tests
        resources :terms
        resources :instructors
        resources :students
        resources :grades

        get 'index' => 'home#index'
=begin
        get 'students' => 'students#index'
        get 'instructors' => 'instructor#index_for_view'
        get 'term' => 'term#index'
        get 'termdeta' => 'termdeta#index'
        get 'test' => 'test#index'
        get 'testdata' => 'testdata#index'
        get 'class' => 'aclasses#index'
        get 'gradelevels' => 'gradelevels#index'
=end

        match '/search' => 'home#search' , :via => [:post , :get]
        match '/student_id' => 'home#student_id' , :via => [:post , :get]
        match '/student_by_tier' => 'home#student_by_tier' , :via => [:post , :get]

end

app/models/grade.rb
# == Schema Information
#
# Table name: grades
#
#  id            :integer          not null, primary key
#  grade         :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  gradelevel_id :integer
#

class Grade < ActiveRecord::Base
	has_many :gradelevel
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades = Grade.all
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to "/grades", notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:grade)
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Add Gradelevel info</strong>
    
  </div><!--

   end top-wizard -->
   

<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <form name="example-1" id="wrapped"  method="POST" >
    <div id="middle-wizard">
      <div class="step">
        <div class="row">
          
          <div class="col-md-6">
            <ul class="data-list">



              <li>
                


                <div class="form-group">
               <%= f.text_field :grade , :type=>"text", :class=>"required form-control", :placeholder=>"Grade" %>
              </i></div></li>

              
              
      
                      
                            
          </div><!-- end col-md-6 -->
                            
          
        </div><!-- end row -->
           </div><!-- end step-->
        <div id="bottom-wizard">
      <%= f.submit :class=>"btn btn-primary " %>
         
      </div>
    </form><!-- end bottom-wizard -->
<% end %> 
    
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->

app/views/grades/edit.html.erb
<h4><center>Update grade</center></h4>

<%= render 'form' %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<section id="wizard_bg">
  <div class="container">
    <!-- Start Survey container -->
    <div id="survey_container">


      <div id="top-wizard">
        <strong>Grade level info</strong>

      </div><!-- end top-wizard -->

      <form name="example-1" id="wrapped" action="http://www.ansonika.com/learn/apply_send.php" method="POST" >
        <div id="middle-wizard">
          <div class="step">


            <center>



              <h4>Listing Grade</h4>



              <table class="table" border="2" style="width:100%">
                <thead>
                <tr>
                  <th>Gradelevel</th>
                  <th>Action</th>
                </tr>
                </thead>

                <tbody>
                <% @grades.each do |grade| %>
                    <tr>
                      <td><%= grade.grade %></td>
                      <td><%= link_to 'Show', grade %>
                      <%= link_to 'Edit', edit_grade_path(grade) %>
                      <%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                <% end %>
                </tbody>
              </table>


<br>



            </center>


          </div><!-- end step-->
          <div id="bottom-wizard">
            <%= link_to 'New Gradelevel', new_grade_path, :class=>"btn btn-primary " %>

            </button>
          </div><!-- end bottom-wizard -->
      </form>

    </div><!-- end Survey container -->

  </div>
</section><!-- end section main container -->

app/views/grades/new.html.erb
<center><h4>Add Grade</h4></center>

<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grade:</strong>
  <%= @grade.grade %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>