config/routes.rb
Rails.application.routes.draw do
  

  
        root to: "home#index"
        devise_for :users

        resources :aclasses
        resources :testdata , :controller=>"gradelevels", :as=>:gradelevels
        resources :termdata
        resources :tests
        resources :terms
        resources :instructors
        resources :students
        resources :grades

        get 'index' => 'home#index'
=begin
        get 'students' => 'students#index'
        get 'instructors' => 'instructor#index_for_view'
        get 'term' => 'term#index'
        get 'termdeta' => 'termdeta#index'
        get 'test' => 'test#index'
        get 'testdata' => 'testdata#index'
        get 'class' => 'aclasses#index'
        get 'gradelevels' => 'gradelevels#index'
=end

        match '/search' => 'home#search' , :via => [:post , :get]
        match '/student_id' => 'home#student_id' , :via => [:post , :get]
        match '/student_by_tier' => 'home#student_by_tier' , :via => [:post , :get]

end

app/models/student.rb
# == Schema Information
#
# Table name: students
#
#  id            :integer          not null, primary key
#  first_name    :string(255)
#  middle_name   :string(255)
#  last_name     :string(255)
#  email         :string(255)
#  date_of_birth :date
#  tier_level    :string(255)
#  phone         :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  gender        :string(255)
#  aclass_id     :integer
#  term_id       :integer
#  testdata_id   :integer
#  testdatum_id  :integer
#


#

class Student < ActiveRecord::Base
	belongs_to :aclass
	#belongs_to :termdatum
	#has_many :tests
	#has_many :terms
	#belongs_to :testdata
	has_many :gradelevels

	######## valdation#############
	validates :aclass_id, presence: true
	#validates :phone, format: { with: /\d{3}-\d{3}-\d{4}/, message: "bad format" }


	def fullname
		return first_name+" "+middle_name+" "+last_name	
	end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_filter :authenticate_user!
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
     puts params[:student][:date_of_birth]
    params[:student][:date_of_birth] = Date::strptime(params[:student][:date_of_birth], "%m/%d/%Y")
    @student = Student.new(student_params)
puts params[:student][:date_of_birth]
puts "**********************"
    respond_to do |format|
      if @student.save
        format.html { redirect_to "/students", notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    puts params[:student][:date_of_birth]
    params[:student][:date_of_birth] = Date::strptime(params[:student][:date_of_birth], "%m/%d/%Y")
    @student = Student.new(student_params)
puts params[:student][:date_of_birth]
puts "**********************"
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :middle_name, :last_name, :email, :date_of_birth, :tier_level, :phone, :gender, :aclass_id, :term_id)
    end
end

app/helpers/students_helper.rb
module StudentsHelper

	def fullname

		return "first_name" +""+"middle_name"+ ""+"last_name"
		
	end
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>

<section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Add Student info</strong>
    
  </div><!-- end top-wizard -->


    <div id="middle-wizard">
      <div class="step">
        <div class="row">
          
          <div class="col-md-6">
            <ul class="data-list">
              <li><div class="form-group"><%= f.text_field :first_name, :class=>"required form-control", :placeholder=>"First name" %><span class="input-icon"><i class="icon-user" ></i></span></div></li>

              <li><div class="form-group">
              <%= f.text_field :middle_name, :class=>"required form-control", :placeholder=>"middle name" %><span class="input-icon"><i class="icon-user"></i></span></div></li>

             <li><div class="form-group"><%= f.text_field :last_name, :class=>"required form-control", :placeholder=>"Last name" %><span class="input-icon"><i class="icon-user"></i></span></div></li>

               <li><div class="form-group"><%= f.text_field :email,:class=>"required form-control", :placeholder=>"Your Email" %><span class="input-icon"><i class="icon-email"></i></span></div></li>
                
       
             
            <li><div class="form-group">
                 <%= f.text_field :date_of_birth, :class=>"form-control",:id=>"end_date" , :placeholder=>" Enter DOB"%><span class="input-icon"><i class="icon-calendar" ></i></span>
                 </div></li>
           

              
            </ul>


            
                            
          </div><!-- end col-md-6 -->
                    
          <div class="col-md-6">
                   
                        
            <ul class="data-list" style="margin:0; padding:0;">
            
                        
             <li><div class="form-group"><%= f.text_field :phone, :class=>"required form-control", :placeholder=>"Your phone number" %><span class="input-icon"><i class="icon-phone"></i></span></div></li>
              
              <!-- <li><div class="form-group"><%#= f.text_field :tier_level, :class=>"required form-control", :placeholder=>"Tier Level (1 , 2, 3)" %></div></li> -->
               

               <li><div class="form-group">
               <%= select_tag "student[aclass_id]", options_from_collection_for_select(Aclass.all , "id", "aclass", @class_id) ,:class=>"form-control",:prompt => " Class of Student" ,:include_blank => "nill" ,:required=>"True" ,:message =>"class need to enter" %>
               
            <% if @student.errors.any? %>
<div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
            </li>



<!-- 
            <h4>Labels Left of Radio buttons</h4>
      
            <div class="form-inline">
                <label class="control-label">
                    What is your favorite season?</label>
                <label class="radio">
                    Winter<input value="1" type="radio">
                </label>
                <label class="radio">
                    Spring<input value="2" type="radio">
                </label>
                <label class="radio">
                    Summer<input value="3" type="radio">
                </label>
                <label class="radio">
                    Autumn (Fall)<input value="4" type="radio">
                </label>
            </div> -->

              <li>
              <div class="form-group">
            <div class="form-inline">
                <label class="control-label">
                    Select Gender</label>&nbsp&nbsp
                <label class="radio">
                    Male <%= f.radio_button :gender, "male"%>
                </label>&nbsp&nbsp
                <label class="radio">
                    Female <%= f.radio_button :gender, "female"%>
                </label>
                </div>
                </div>
                </li>
                <li>
                <div class="form-group">
                <div class="form-inline">
                <label class="control-label">
                    Select Tier&nbsp&nbsp</label>&nbsp&nbsp
                <label class="radio">
                     Tier 1 <%= f.radio_button :tier_level, "Tier 1"%>
                </label>&nbsp&nbsp
                <label class="radio">
                    Tier 2 <%= f.radio_button :tier_level, "Tier 2"%>
                </label>&nbsp&nbsp
                <label class="radio">
                    Tier 3 <%= f.radio_button :tier_level, "Tier 3"%>
                    </label>
                </div>
                </div>
                </li>

      <!-- div class="control-group">
        
               <div class="controls">
             <p> Select Gender :</p>
              <label for="male">Male</label>


              <%#= f.radio_button :gender, "male"%><br>
              <label for="female">Female</label>
               <%#= f.radio_button :gender, "female"%><br><br>
        </div>
        </div>
 -->
         </ul>

          </div><!-- end col-md-6 -->
        </div><!-- end row -->
           </div><!-- end step-->
       <div class="actions" id="bottom-wizard">
          <%= f.submit :class=>"btn btn-primary" %>
      <%= link_to 'Back', students_path, :class=>"btn btn-primary" %>
      </div>

     <% end %>
    
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->

app/views/students/edit.html.erb
<h4><center>Update student</center></h4> 

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
 <section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Student info</strong>
    
  </div><!-- end top-wizard -->
    
  
    <div id="middle-wizard">
      <div class="step">

          
         <center>
          
           <h3>Listing students</h3>


        <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
              <th>First name</th>
              <th>Middle name</th>
              <th>Last name</th>
              <th>Email</th>
              <th>Date of birth</th>
              <th>Phone</th>
              <th>Gender</th>
              <th>Tier level</th>
              <th>Class of Student</th>
              <th>Action</th>
            </tr>
        </thead>
 
        <tbody>
          <% @students.each do |student| %>
            <tr>  
                  
                  <td><%= student.first_name %></td>
                  <td><%= student.middle_name %></td>
                  <td><%= student.last_name %></td>
                  <td><%= student.email %></td>
                  <td><%= student.date_of_birth %></td>
                  <td><%= student.phone %></td>
                  <td><%= student.gender %></td>
                  <td><%= student.tier_level %></td>

                  <td><%= student.aclass.aclass rescue "" %></td>


                  <td> <%= link_to 'Show', student %> <%= link_to 'Edit', edit_student_path(student) %> <%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
           <% end %>
        </tbody>
    </table>
      


<br>

   
            
                            
         </center>
          
      
           </div><!-- end step-->
        <div id="bottom-wizard">
          <%= link_to 'New Student', new_student_path , :class=>"btn btn-primary " %>
         
         </button>
      </div><!-- end bottom-wizard -->
  </form>
    
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
 <section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Student info</strong>
    
  </div><!-- end top-wizard -->
    
  
    <div id="middle-wizard">
      <div class="step">

          
         <center>
            <p id="notice"><%= notice %></p>
             <table border="2" width="40%" BGCOLOR="#99CCFF" style="text-align:center;">
               <tr colspan="3">
                 <th>First name:</th>
                 <td> <%= @student.first_name %></td>
               </tr>
               <tr>
                 <th>Middle name:</th>
                 <td><%= @student.middle_name %></td>
               </tr>
               <tr>
                 <th>Last name:</th>
                 <td>  <%= @student.last_name %></td>
               </tr>
                <tr>
                 <th>Email:</th>
                 <td>  <%= @student.email %></td>
               </tr>
                 <tr>
                 <th>Date of birth:</th>
                 <td> <%= @student.date_of_birth %></td>
               </tr>
                 <tr>
                 <th>Tier level:</th>
                 <td> <%= @student.tier_level %></td>
               </tr>
                <tr>
                 <th>Phone:</th>
                 <td> <%= @student.phone %></td>
               </tr>
                <tr>
                 <th>Gender:</th>
                 <td> <%= @student.gender %></td>
               </tr>
             </table>
             
   
            
                            
         </center>
          
      
           </div><!-- end step-->
        <div id="bottom-wizard">
          <%= link_to 'Edit', edit_student_path(@student), :class=>"btn btn-primary " %>
          <%= link_to 'Back', students_path, :class=>"btn btn-primary " %>
         </button>
      </div><!-- end bottom-wizard -->
 
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->




<script type="text/javascript">
      $(document).ready(function() {
        $('#example').dataTable();
      } );
    </script>