config/routes.rb
Rails.application.routes.draw do
  

  
        root to: "home#index"
        devise_for :users

        resources :aclasses
        resources :testdata , :controller=>"gradelevels", :as=>:gradelevels
        resources :termdata
        resources :tests
        resources :terms
        resources :instructors
        resources :students
        resources :grades

        get 'index' => 'home#index'
=begin
        get 'students' => 'students#index'
        get 'instructors' => 'instructor#index_for_view'
        get 'term' => 'term#index'
        get 'termdeta' => 'termdeta#index'
        get 'test' => 'test#index'
        get 'testdata' => 'testdata#index'
        get 'class' => 'aclasses#index'
        get 'gradelevels' => 'gradelevels#index'
=end

        match '/search' => 'home#search' , :via => [:post , :get]
        match '/student_id' => 'home#student_id' , :via => [:post , :get]
        match '/student_by_tier' => 'home#student_by_tier' , :via => [:post , :get]

end

app/models/instructor.rb
# == Schema Information
#
# Table name: instructors
#
#  id          :integer          not null, primary key
#  first_name  :string(255)
#  middle_name :string(255)
#  last_name   :string(255)
#  email       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  gender      :string(255)
#  aclass_id   :integer
#

class Instructor < ActiveRecord::Base
	has_one :aclass


	def full_name
		return first_name+" "+last_name	
		
	end
	
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!
  
  # GET /instructors
  # GET /instructors.json


  def index_for_view
    
  end
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
   
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to "/instructors", notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end





  def search
    
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:first_name, :middle_name, :last_name, :email, :gender ,:aclass_id)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
<% if @instructor.errors.any? %>
 <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Add Instructor info</strong>
    
  </div><!-- end top-wizard -->
  
    
  
    <div id="middle-wizard">
      <div class="step">
        <div class="row">
          
          <div class="col-md-6">
            <ul class="data-list">


              <li><div class="form-group"> <%= f.text_field :first_name , :class=>"required form-control", :placeholder=>"First name" %><span class="input-icon"><i class="icon-user"></i></span></div></li>

              <li><div class="form-group"> <%= f.text_field :middle_name, :class=>"required form-control", :placeholder=>"middle name" %><span class="input-icon"><i class="icon-user"></i></span></div></li>

              <li><div class="form-group"><%= f.text_field :last_name, :class=>"required form-control", :placeholder=>"Last name" %><span class="input-icon"><i class="icon-user"></i></span></div></li>

              <li><div class="form-group"><%= f.text_field :email, :class=>"required form-control" , :placeholder=>"Your Email",:required=>"True"  %><span class="input-icon"><i class="icon-email"></i></span></div></li>
                        

             <!--  <li><div class="form-group">
              <% aclass = @instructor.aclass.aclass rescue ""%> 
               <%#= select_tag "instructor[aclass_id]", options_from_collection_for_select(Aclass.all , "id", "aclass",aclass ) ,:class=>"form-control",:prompt => "Assign Instructor To Class" ,:required=>"True", :value => "#{@instructor.aclass_id}"   %>

            </li> -->
            <li>
               <p> Select Gender :</p>
              <label for="male">Male</label>
              <%= f.radio_button :gender, "male"%><br>
              <label for="female">Female</label>
               <%= f.radio_button :gender, "female"%><br><br>
               </li>
             

                            
          </div><!-- end col-md-6 -->
                    
          
        </div><!-- end row -->
           </div><!-- end step-->
        <div id="bottom-wizard" class="actions">
          <%= f.submit :class=>"btn btn-primary " %>
         </button>
      </div><!-- end bottom-wizard -->
      <% end %>
  
    
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->

app/views/instructors/edit.html.erb
<h4><center>Update Instructor</center></h4>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="mobnav-btn"></div>
     


           
              </div><!-- End search -->

    </div>
  </div><!-- End row -->
</div><!-- End container -->
</nav>


 <section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Instructor Info </strong>
    
  </div><!-- end top-wizard -->
    

    <div id="middle-wizard">
      <div class="step">

          
         <center>
          <h3>Listing instructors</h3>

<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
               <th>Class name</th>
               <th>First name</th>
              <th>Middle name</th>
               <th>Last name</th>
               <th>Email</th>
               <th>Gender</th>
               
               <th>Action</th>
            </tr>
        </thead>
 
       
 
        <tbody>
         <% @instructors.each do |instructor| %>
            <tr>
                <td><%=instructor.aclass.aclass rescue "" %></td>
                <td><%=instructor.first_name rescue ""%> </td>
                <td><%=instructor.middle_name rescue ""%></td>
                <td><%=instructor.last_name rescue ""%></td>
                <td><%=instructor.email rescue ""%></td>
                <td><%=instructor.gender rescue "" %></td>
                
               <td><%= link_to 'Show', instructor %>
        <%= link_to 'Edit', edit_instructor_path(instructor) %>
        <%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
           
           <%end%>
        </tbody>
    </table>


<br>
                      
         </center>
          
      
           </div><!-- end step-->
        <div id="bottom-wizard">
          <%= link_to 'New Instructor', new_instructor_path, :class=>"btn btn-primary " %>
        
         </button>
      </div><!-- end bottom-wizard -->
 
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->




  <script type="text/javascript">
      $(document).ready(function() {
        $('#example').dataTable();
         "paging":   false,
        "ordering": false,
        "info":     false
      } );
    </script>

app/views/instructors/index_for_view.html.erb
<!-- End login -->
<section id="sub-header">
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1 text-center">
			<h2>Faculty page is under construction</h2>
			<p class="lead boxed">You will be able to Access this page soon...</p>
			<p class="lead">
				Lorem ipsum dolor sit amet, ius minim gubergren ad. At mei sumo sonet audiam, ad mutat elitr platonem vix. Ne nisl idque fierent vix. 
			</p>
		</div>
	</div><!-- End row -->
</div><!-- End container -->
<div class="divider_top"></div>
</section><!-- End sub-header -->

app/views/instructors/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
 <section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Student info</strong>
    
  </div><!-- end top-wizard -->
    
  <form name="example-1" id="wrapped" action="http://www.ansonika.com/learn/apply_send.php" method="POST" >
    <div id="middle-wizard">
      <div class="step">

          
         <center>
                      
          <p id="notice"><%= notice %></p>
            <table border="2" width="40%" BGCOLOR="#99CCFF" style="text-align:center;">
              <tr colspan="3">
                <th>First name:</th>
                <td><%= @instructor.first_name %></td>
              </tr>
              <tr>
                <th>Middle name:</th>
                <td><%= @instructor.middle_name %></td>
              </tr>
              <tr>
                <th>Last name:</th>
                <td> <%= @instructor.last_name %></td>
              </tr>
               <tr>
                <th>Email:</th>
                <td> <%= @instructor.email %></td>
              </tr>
               <tr>
                <th>Gender:</th>
                <td> <%= @instructor.gender %></td>
              </tr>
            </table>
            
            
                        
                            
         </center>
          
      
           </div><!-- end step-->
        <div id="bottom-wizard">
          <%= link_to 'Edit', edit_instructor_path(@instructor), :class=>"btn btn-primary " %>
         <%= link_to 'Back', instructors_path, :class=>"btn btn-primary" %>
         </button>
      </div><!-- end bottom-wizard -->
  </form>
    
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->