config/routes.rb
Rails.application.routes.draw do
  

  
        root to: "home#index"
        devise_for :users

        resources :aclasses
        resources :testdata , :controller=>"gradelevels", :as=>:gradelevels
        resources :termdata
        resources :tests
        resources :terms
        resources :instructors
        resources :students
        resources :grades

        get 'index' => 'home#index'
=begin
        get 'students' => 'students#index'
        get 'instructors' => 'instructor#index_for_view'
        get 'term' => 'term#index'
        get 'termdeta' => 'termdeta#index'
        get 'test' => 'test#index'
        get 'testdata' => 'testdata#index'
        get 'class' => 'aclasses#index'
        get 'gradelevels' => 'gradelevels#index'
=end

        match '/search' => 'home#search' , :via => [:post , :get]
        match '/student_id' => 'home#student_id' , :via => [:post , :get]
        match '/student_by_tier' => 'home#student_by_tier' , :via => [:post , :get]

end

app/models/gradelevel.rb
# == Schema Information
#
# Table name: gradelevels
#
#  id         :integer          not null, primary key
#  gradelevel :string(255)
#  aclass_id  :integer
#  created_at :datetime
#  updated_at :datetime
#  test_id    :integer
#  student_id :integer
#  grade_id   :integer
#  benchmark  :string(255)
#

class Gradelevel < ActiveRecord::Base
	belongs_to :grade
	belongs_to :student
	belongs_to :test
end

app/controllers/gradelevels_controller.rb
class GradelevelsController < ApplicationController
    before_filter :authenticate_user!
  before_action :set_gradelevel, only: [:show, :edit, :update, :destroy]

  # GET /gradelevels
  # GET /gradelevels.json
  def index
    @gradelevels = Gradelevel.all
  end

  # GET /gradelevels/1
  # GET /gradelevels/1.json
  def show
  end

  # GET /gradelevels/new
  def new
    @gradelevel = Gradelevel.new
        @classes = Aclass.all
        @tests = []
        if !params[:aclass_id].blank?
         
             @class = Aclass.find_by_id(params[:aclass_id]) 
             @class_id = @class.id
             @terms  = @class.terms
             @term_id = (params[:term_id])
             @students =[]
             
       elsif !params[:term_id].blank?
          @term =Term.find_by_id(params[:term_id])
           @class = @term.aclass
            @class_id = @class.id
             @terms  = @class.terms
            @term_id = (params[:term_id])
             #@test_id = @gradelevel.test.id
            @tests = @term.tests
            @students =@class.students
          elsif !params[:test_id].blank?
          @test =Test.find_by_id(params[:test_id])
          @test_id=@test.id
          @term=@test.term
          @term_id = @term.id
           @class = @term.aclass
            @class_id = @class.id
             @terms  = @class.terms
            
             #@test_id = @gradelevel.test.id
            @tests = @term.tests
            @students =@class.students
      else 
            @class_id = "" 
            @classes = Aclass.all
            @terms = [] 
            @students = [] 
       end

      # @students =@class.students
  end

  # GET /gradelevels/1/edit
  def edit
     @classes = Aclass.all
        @tests = []
        @student_id = @gradelevel.student_id
    @term =@gradelevel.test.term
           @class = @term.aclass
            @class_id = @class.id
             @terms  = @class.terms
            @term_id = @term.id
            @test_id = @gradelevel.test.id
             @student_id=@gradelevel.student.id
            @tests = @term.tests
            @students =@class.students
      if !params[:aclass_id].blank?
         
             @class = Aclass.find_by_id(params[:aclass_id]) 
             @class_id = @class.id
             @terms  = @class.terms
             @term_id = (params[:term_id])
             @students =[]
             
       elsif !params[:term_id].blank?
          @term =Term.find_by_id(params[:term_id])
           @class = @term.aclass
            @class_id = @class.id
             @terms  = @class.terms
            @term_id = (params[:term_id])
             #@test_id = @gradelevel.test.id
            @tests = @term.tests
            @students =@class.students
          elsif !params[:test_id].blank?
          @test =Test.find_by_id(params[:test_id])
          @test_id=@test.id
          @term=@test.term
          @term_id = @term.id
           @class = @term.aclass
            @class_id = @class.id
             @terms  = @class.terms
            
             #@test_id = @gradelevel.test.id
            @tests = @term.tests
            @students =@class.students
          end
  end

  # POST /gradelevels
  # POST /gradelevels.json
  def create
    @gradelevel = Gradelevel.new(gradelevel_params)

    respond_to do |format|
      if @gradelevel.save
        format.html { redirect_to "/testdata", notice: 'Gradelevel was successfully created.' }
        format.json { render :show, status: :created, location: @gradelevel }
      else
        format.html { render :new }
        format.json { render json: @gradelevel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gradelevels/1
  # PATCH/PUT /gradelevels/1.json
  def update
    respond_to do |format|
      if @gradelevel.update(gradelevel_params)
        format.html { redirect_to @gradelevel, notice: 'Gradelevel was successfully updated.' }
        format.json { render :show, status: :ok, location: @gradelevel }
      else
        format.html { render :edit }
        format.json { render json: @gradelevel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gradelevels/1
  # DELETE /gradelevels/1.json
  def destroy
    @gradelevel.destroy
    respond_to do |format|
      format.html { redirect_to gradelevels_url, notice: 'Gradelevel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gradelevel
      @gradelevel = Gradelevel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gradelevel_params
      params.require(:gradelevel).permit(:gradelevel, :term_id, :aclass_id, :test_id,:student_id, :grade_id)
    end
end

app/helpers/gradelevels_helper.rb
module GradelevelsHelper
end

app/views/gradelevels/_form.html.erb
  
 
<section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Add Test Data </strong>
    
  </div><!--

   end top-wizard -->
   <%= form_for(@gradelevel) do |f| %>

  <% if @gradelevel.errors.any? %>

      <h2><%= pluralize(@gradelevel.errors.count, "error") %> prohibited this gradelevel from being saved:</h2>

      <ul>
      <% @gradelevel.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <form name="example-1" id="wrapped"  method="POST" >
    <div id="middle-wizard">
      <div class="step">
        <div class="row">
          
          <div class="col-md-6">
            <ul class="data-list">

               <li><div class="form-group">
               <%= select_tag "gradelevel[aclass_id]", options_from_collection_for_select(@classes, "id", "aclass",@class_id) ,:class=>"form-control",:prompt => "All Classes"  ,:id =>"aclass"  ,:onchange =>"window.location.assign('?aclass_id='+document.getElementById('aclass').value)",:value => "@testdata" ,:required=>"True"%>
               
            </li>


              </li>
             <li><div class="form-group">
               <%= select_tag "term_id", options_from_collection_for_select(@terms, "id", "term",@term_id) ,:class=>"form-control",:prompt => "Select Term"  ,:id =>"term"  ,:onchange =>"window.location.assign('?term_id='+document.getElementById('term').value)",:value => "@testdata" ,:required=>"True"%>
               
            </li>
             <li><div class="form-group">
             <%#=inspect.@class %>
               <%= select_tag "gradelevel[test_id]", options_from_collection_for_select(@tests, "id", "name",@test_id)  ,{ :prompt => 'Select Test',:id=>"test",:onchange =>"window.location.assign('?test_id='+document.getElementById('test').value)",:class=>"form-control" ,:required=>"True"} %>
            </li>


           <li><div class="form-group">
             <%#=inspect.@class %>
               <%= select_tag "gradelevel[student_id]", options_from_collection_for_select(@students, "id", "fullname",@student_id)  ,{ :prompt => 'Select Student',:class=>"form-control",:required=>"True"} %>
            </li>



            <li><div class="form-group">
                 <%#=inspect.@class %>
               <%= select_tag "gradelevel[grade_id]", options_from_collection_for_select(Grade.all, "id", "grade",@student_id)  ,{ :prompt => 'Assign Grade',:class=>"form-control",:required=>"True"} %>
            </li>

            <li>
                <div class="form-group">
                <div class="form-inline">
                <label class="control-label">
                    Add BenchMark &nbsp&nbsp</label>&nbsp&nbsp
                <label class="radio">
                     Good <%= f.radio_button :benchmark, "Good"%>
                </label>&nbsp&nbsp
                <label class="radio">
                    Fair <%= f.radio_button :benchmark, "Fair"%>
                </label>&nbsp&nbsp
                <label class="radio">
                    Poor <%= f.radio_button :benchmark, "Poor"%>
                    </label>
                    <label class="radio">
                    Excellent <%= f.radio_button :benchmark, "Excellent"%>
                    </label>
                </div>
                </div>
                </li>
  
  

 
 


        
                


<!-- 
                <div class="form-group">
               <%#= f.text_field :gradelevel , :type=>"text", :class=>"required form-control", :placeholder=>"Gradelevel" %>
              </i></div></li>
                
          </div><!-end col-md-6 --> 
                            
          
        </div><!-- end row -->
           </div><!-- end step-->
        <div id="bottom-wizard">
      <%= f.submit " Create TestData",:class=>"btn btn-primary " %>
         <%= link_to 'Back', gradelevels_path ,:class=>"btn btn-primary " %>

      </div>
    </form><!-- end bottom-wizard -->
<% end %> 
    
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->

app/views/gradelevels/edit.html.erb
<h4><center>Update gradelevel</center></h4>

<%= render 'form' %>

<%= link_to 'Show', @gradelevel %> |
<%= link_to 'Back', gradelevels_path %>

app/views/gradelevels/index.html.erb
 <section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Add Test Data</strong>
    
  </div><!-- end top-wizard -->
    
  
    <div id="middle-wizard">
      <div class="step">

          
         <center>
                      
                  
        
        <h4>Listing Test Data</h4>

           <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">

                   <thead>
                     <tr>
                     <th>Class</th>
                     <th>Student Name</th>
                      <th>Term</th>
                       <th>Test</th>
                       <th>Assigned Grade</th>
                       <th>Assigned Grade</th>

                       <th>Action</th>
                     </tr>
                   </thead>
                 
                   <tbody>
                     <% @gradelevels.each do |gradelevel| %>
                       <tr>
                       <td><%= gradelevel.student.aclass.aclass  rescue ""%></td>
                       <td><%= gradelevel.student.fullname rescue "" %></td>
                       <td><%= gradelevel.test.term.term  rescue "" %></td>
                         <td><%= gradelevel.test.name rescue ""  %>
                         <td><%= gradelevel.grade.grade rescue "" %></td>
                         <td><%= gradelevel.benchmark rescue "" %></td>
                         <td><%= link_to 'Show', gradelevel %>
                         <%= link_to 'Edit', edit_gradelevel_path(gradelevel) %>
                         <%= link_to 'Destroy', gradelevel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                       </tr>
                     <% end %>
                   </tbody>
                 </table>

             
            
            
                        
                            
         </center>
          
      
           </div><!-- end step-->
        <div id="bottom-wizard">
         <%= link_to 'New Test Data', new_gradelevel_path, :class=>"btn btn-primary " %>
        
         </button>
      </div><!-- end bottom-wizard -->

</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->
 <script type="text/javascript">
     $(document).ready(function() {
         $('#example').dataTable();

                 "ordering": false,
                 "info":     false
     } );
 </script>

app/views/gradelevels/new.html.erb
<%= render 'form' %>

app/views/gradelevels/show.html.erb
<!-- <p id="notice"><%= notice %></p>
<table border="2" width="40%" BGCOLOR="#99CCFF" style="text-align:center;">
  <tr colspan="3">
    <th>Gradelevel:</th>
    <td>  <%= @gradelevel.gradelevel.inspect %></td>
  </tr>
  
</table>


<%= link_to 'Edit', edit_gradelevel_path(@gradelevel) %> |
<%= link_to 'Back', gradelevels_path %>
 -->

<body>

  <header>
  <center> <a href="/index"><h2>Reeves Elementary School Digital Wall</h2></center>
    <div class="container">
  <div class="row">
    <div class="col-md-3 col-sm-3 col-xs-3">
      <a href="#"></a>
    </div>
    
  </div>
</div>
</header><!-- End header -->

<nav>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div id="mobnav-btn"></div>
     


           
              </div><!-- End search -->

    </div>
  </div><!-- End row -->
</div><!-- End container -->
</nav>


 <section id="wizard_bg">
<div class="container">
<!-- Start Survey container -->
<div id="survey_container">


  <div id="top-wizard">
    <strong>Grade level info</strong>
    
  </div><!-- end top-wizard -->
    
  <form name="example-1" id="wrapped" action="http://www.ansonika.com/learn/apply_send.php" method="POST" >
    <div id="middle-wizard">
      <div class="step">

          
         <center>
                      
                  
        
           <p id="notice"><%= notice %></p>
            <table border="2" width="40%" BGCOLOR="#99CCFF" style="text-align:center;">
              <tr colspan="3">
                <th>Gradelevel:</th>
                <td>  <%= @gradelevel.gradelevel %></td>
              </tr>
              
            </table>

             
            
            
                        
                            
         </center>
          
      
           </div><!-- end step-->
        <div id="bottom-wizard">
         <%= link_to 'Edit', edit_gradelevel_path(@gradelevel), :class=>"btn btn-primary " %>
         <%= link_to 'Back', gradelevels_path, :class=>"btn btn-primary " %>
         </button>
      </div><!-- end bottom-wizard -->
  </form>
    
</div><!-- end Survey container -->

</div>
</section><!-- end section main container -->





<footer>
<hr>
<div class="container" id="nav-footer">
  <div class="row text-left">
    <div class="col-md-3 col-sm-3">
      <h4>Browse</h4>
      <ul>
        <li><a href="prices_plans.html">Prices</a></li>
        <li><a href="courses_grid.html">Courses</a></li>
        <li><a href="blog.html">Blog</a></li>
        <li><a href="contacts.html">Contacts</a></li>
      </ul>
    </div><!-- End col-md-4 -->
    <div class="col-md-3 col-sm-3">
      <h4>Next Courses</h4>
      <ul>
        <li><a href="course_details_1.html">Biology</a></li>
        <li><a href="course_details_2.html">Management</a></li>
        <li><a href="course_details_2.html">History</a></li>
        <li><a href="course_details_3.html">Litterature</a></li>
      </ul>
    </div><!-- End col-md-4 -->
    <div class="col-md-3 col-sm-3">
      <h4>About Learn</h4>
      <ul>
        <li><a href="about_us.html">About Us</a></li>
        <li><a href="apply_2.html">Apply</a></li>
        <li><a href="#">Terms and conditions</a></li>
        <li><a href="register.html">Register</a></li>
      </ul>
    </div><!-- End col-md-4 -->
    <div class="col-md-3 col-sm-3">
      <ul id="follow_us">
        <li><a href="#"><i class="icon-facebook"></i></a></li>
        <li><a href="#"><i class="icon-twitter"></i></a></li>
        <li><a href="#"><i class=" icon-google"></i></a></li>
      </ul>
      <ul>
        <li><strong class="phone">+0034 43244 44</strong><br><small>Mon - Fri / 9.00AM - 06.00PM</small></li>
        <li>Questions? <a href="#"><span class="__cf_email__" data-cfemail="d9a8acbcaaadb0b6b7aa99bdb6b4b8b0b7f7bab6b4">[email&nbsp;protected]</span><script type="text/javascript">
/* <![CDATA[ */
(function(){try{var s,a,i,j,r,c,l,b=document.getElementsByTagName("script");l=b[b.length-1].previousSibling;a=l.getAttribute('data-cfemail');if(a){s='';r=parseInt(a.substr(0,2),16);for(j=2;a.length-j;j+=2){c=parseInt(a.substr(j,2),16)^r;s+=String.fromCharCode(c);}s=document.createTextNode(s);l.parentNode.replaceChild(s,l);}}catch(e){}})();
/* ]]> */
</script></a></li>
      </ul>
    </div><!-- End col-md-4 -->
  </div><!-- End row -->
</div>
<div id="copy_right">© 1998-2014</div>
</footer>

<div id="toTop">Back to top</div>



  </body>
</html>